version: "3"
services:
    springapp:
      build: .
      container_name: library-spring
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/librarydb
      ports:
        - 8000:8080
      restart: always
      depends_on:
        - db
    db:
      image: postgres
      container_name: db
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=librarydb
        - PGDATA=/var/lib/postgresql/data/pgdata
      ports:
        - 5000:5432
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: always
volumes:
    pgdata: